### ISSUE TITLE
バグ？

### ISSUE THREAD

**Issue by Ubugeeei** [cohky16/invite#23]
改行してメッセージを送ると起動しない

https://user-images.githubusercontent.com/71201308/149634355-a83e6688-6069-42cb-833c-b02e4492d739.mov

**Comment by cohky16** [comment]
goの正規表現でバグってるっぽい

**Comment by cohky16** [comment]
@Ubugeeei 

報告ありがとうございます！対応しました！

https://github.com/cohky16/invite/pull/24
